## Task 2
 Implement the Viterbi algorithm in a programming language of your choice (we recommend python). Please submit your code and the output files archived together with the latex report. The output files need to be in the same format as the given example output file.
The HMM has three states S1, S2, S3, and four observations W, X, Y, Z. In the output files, the states are labeled only by the numbers 1, 2, 3

In [171]:
import numpy as np
import math

### Point c
Lets define a random starting P_t and use the first equation to updated it until it converges

In [23]:
Pt = np.array([0.3, 0.3, 0.4]);
Ptold = np.array([0, 0, 0]);
AT = np.transpose(A);
epsilon = 1e-9;
while(np.absolute(Ptold[0] - Pt[0]) > epsilon 
        or np.absolute(Ptold[1] - Pt[1]) > epsilon 
        or np.absolute(Ptold[2] - Pt[2]) > epsilon):
    Ptold = Pt;
    Pt = np.dot(AT, Ptold);
    print(Pt)
    


[0.34 0.26 0.4 ]
[0.316 0.26  0.424]
[0.3256 0.2696 0.4048]
[0.32368 0.26192 0.4144 ]
[0.322912 0.26576  0.411328]
[0.3239872 0.2645312 0.4114816]
[0.32331136 0.26459264 0.412096  ]
[0.32359398 0.2648384  0.41156762]
[0.32353009 0.26462705 0.41184287]
[0.32351337 0.26473715 0.41174948]
[0.32354208 0.26469979 0.41175813]
[0.32352313 0.26470325 0.41177362]
[0.3235314  0.26470945 0.41175915]
[0.32352933 0.26470366 0.41176701]
[0.323529  0.2647068 0.4117642]
[0.32352976 0.26470568 0.41176456]
[0.32352923 0.26470582 0.41176494]
[0.32352947 0.26470598 0.41176455]
[0.32352941 0.26470582 0.41176477]
[0.3235294  0.26470591 0.41176469]
[0.32352942 0.26470588 0.4117647 ]
[0.32352941 0.26470588 0.41176471]
[0.32352941 0.26470588 0.4117647 ]
[0.32352941 0.26470588 0.41176471]
[0.32352941 0.26470588 0.41176471]
[0.32352941 0.26470588 0.41176471]


### Point d
implement Viterbi's algorithm using $Ps = Pt$ as initial probabilities

$delta_1(i) = Pi(i)b_i(O_1)$

In [176]:
possibleO=['W','X','Y','Z'];
#some observation sequences are very long -> USE LOG!
def viterbi(pi, obs):
    nb_states=len(pi);
    delta = np.zeros((len(obs), nb_states))
    sequences = np.zeros((len(obs), nb_states)).astype(int)
    id_o1 = possibleO.index(obs[0])
    for i in range(nb_states):
        # delta[0,i] = pi[i]*B[i,id_o1];
        delta[0,i] = math.log(pi[i]) + math.log(B[i,id_o1]);
        sequences[0,i] = i;
    for t in range(1,len(obs)):
        id_ot = possibleO.index(obs[t]);
        for i in range(nb_states):
            for j in range(nb_states):
                # pij = delta[t-1,i]*A[i,j] * B[j,id_ot]
                # pij = math.log(delta[t-1,i]) + math.log(A[i,j]) + math.log(B[j,id_ot])
                pij = 0
                if (delta[t-1,i] > 0): pij += math.log(delta[t-1,i])
                if (A[i,j] > 0): pij += math.log(A[i,j])
                if (B[j,id_ot] > 0): pij += math.log(B[j,id_ot])
                if (pij > delta[t,j]): 
                    delta[t,j] = pij
                    sequences[t,j] = i;
    print(delta)
    #print(sequences)
    sequence = list()
    sequence.append(np.argmax(delta[len(obs)-1]))
    for i in range(1, len(obs)):
        id_t = len(obs)-i
        sequence.append(sequences[id_t, sequence[i-1]])
    sequence.reverse()
    return sequence

In [180]:
A = np.array([[0,0.1,0.9], [0.6,0.1,0.3], [0.4,0.5,0.1]])
B = np.array([[0.6,0.1,0.2,0.1],[0.1,0.7,0.1,0.1],[0.2,0,0.5,0.3]])
print(B)
pi = np.array([0.32352941, 0.26470588, 0.41176471]);
obs = list('WWXXWZWXWYYXXYXYWZXWZZWYZ')
res=viterbi(pi, obs)
res_str = ''.join([str(a) for a in res])
print(math.log(-1))

[[0.6 0.1 0.2 0.1]
 [0.1 0.7 0.1 0.1]
 [0.2 0.  0.5 0.3]]
[[-1.63929088 -3.63172105 -2.4967411 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0. 

ValueError: math domain error

ValueError: math domain error